; пример конфигурационного файла
[Section1]; секция с основными настройками
var1 = 5.0 ; допускается комментарий после значения
var2 = какая-то строка

[Section2]
var1 = 1
var2 = значение_2

; Section3 объявлена, но не содержит переменных
[Section3]

[Section4]
Mode = release
Level = 3

; секции могут повторяться — переменные добавляются в ту же секцию,
; а значение var1 из [Section1] будет переприсвоено
[Section1]
var3 = значение
var1 = 1.0
